import numpy as np

team_nicknames= np.array([
    'Eagles',
    'Dragons',
    'Raccoons',
    'Comets',
    'Bears',
    'Lions',
    'Wildcats',
    'Rhinos',
    'Tortoises',
    'Falcons',
    'Kangaroos',
    'Panthers',
    'Zebras',
    'Griffins',
    'Cobras',
    'Dinosaurs',
    'Aviators',
    'Bison',       
    'Wolves',
    'Cheetahs',
    'Sharks',
    'Phoenixes',
    'Tornadoes',
    'Cyclones',
    'Rabbits',
    'Goats',
    'Knights',
    'Giants',
    'Crocodiles',
    'Mustangs'
])